In [9]:
import numpy as np
import PIL
from PIL import Image
import os
from skimage.io import imread
from skimage import color
from skimage.transform import resize

In [10]:
import tensorflow as tf

In [11]:
def load_and_resize(path, size):
    resized_pics=[]
    # print(path)
    for roots,dirs,files in os.walk(path):
        for file in files:
            filename,ext = os.path.splitext(file)
            # print(filename)
            img = imread(roots +"/" + file)
            img = resize(img, size)
            resized_pics.append(img)
    return resized_pics
    

In [13]:
pics=load_and_resize("dataset/beach",(64,64))

In [14]:
for pic in pics:
    display(pic)

array([[[0.36259191, 0.57640931, 0.75860907],
        [0.33465074, 0.57911497, 0.75297181],
        [0.34445466, 0.59215112, 0.76473652],
        ...,
        [0.        , 0.45490196, 0.6745098 ],
        [0.        , 0.45490196, 0.6745098 ],
        [0.        , 0.45490196, 0.6745098 ]],

       [[0.30003064, 0.59598652, 0.73738703],
        [0.27208946, 0.59607843, 0.72689951],
        [0.26710899, 0.60009191, 0.72576593],
        ...,
        [0.        , 0.45490196, 0.67068015],
        [0.        , 0.4510723 , 0.67068015],
        [0.        , 0.4510723 , 0.67068015]],

       [[0.30382966, 0.56900084, 0.75428347],
        [0.26927083, 0.56516544, 0.73832721],
        [0.25520833, 0.56127259, 0.72941176],
        ...,
        [0.        , 0.45098039, 0.66289828],
        [0.        , 0.45098039, 0.66289828],
        [0.00171569, 0.45098039, 0.66289828]],

       ...,

       [[0.64789752, 0.46765855, 0.25620021],
        [0.73300398, 0.5422258 , 0.33856273],
        [0.83458563, 0

array([[[0.37702206, 0.37337623, 0.16280637],
        [0.5359375 , 0.62815564, 0.16448328],
        [0.56633301, 0.65263145, 0.1588848 ],
        ...,
        [0.18241422, 0.44908088, 0.94117647],
        [0.17254902, 0.43731618, 0.94319853],
        [0.16862745, 0.43921569, 0.94901961]],

       [[0.54000412, 0.57374387, 0.20221402],
        [0.61151338, 0.71372549, 0.18620701],
        [0.48050465, 0.62673627, 0.17213015],
        ...,
        [0.20214461, 0.4627451 , 0.94509804],
        [0.18645833, 0.45098039, 0.94901961],
        [0.18253676, 0.453125  , 0.94901961]],

       [[0.55413603, 0.60903799, 0.18823529],
        [0.51803529, 0.68566176, 0.1580576 ],
        [0.41884191, 0.62276348, 0.14901961],
        ...,
        [0.22352941, 0.4745098 , 0.94283088],
        [0.21011029, 0.46501225, 0.94483236],
        [0.2240536 , 0.47677696, 0.94509804]],

       ...,

       [[0.95686275, 0.96470588, 0.91372549],
        [0.9591299 , 0.96497156, 0.91764706],
        [0.9586871 , 0

array([[[0.04313725, 0.29411765, 0.59607843],
        [0.03921569, 0.29411765, 0.59607843],
        [0.03921569, 0.29803922, 0.6       ],
        ...,
        [0.13823529, 0.1745098 , 0.0627451 ],
        [0.27058824, 0.3127451 , 0.1254902 ],
        [0.19803922, 0.22352941, 0.11764706]],

       [[0.02745098, 0.29803922, 0.6       ],
        [0.03137255, 0.30098039, 0.60392157],
        [0.03529412, 0.30196078, 0.60784314],
        ...,
        [0.16568627, 0.20392157, 0.06666667],
        [0.25490196, 0.27843137, 0.12647059],
        [0.1754902 , 0.20294118, 0.10980392]],

       [[0.02745098, 0.30196078, 0.60392157],
        [0.03137255, 0.30196078, 0.60784314],
        [0.03137255, 0.30588235, 0.61176471],
        ...,
        [0.19411765, 0.23333333, 0.0872549 ],
        [0.2372549 , 0.25784314, 0.12254902],
        [0.14901961, 0.18431373, 0.08627451]],

       ...,

       [[0.9254902 , 0.90980392, 0.89411765],
        [0.92941176, 0.90980392, 0.89803922],
        [0.93333333, 0

array([[[0.        , 0.33333333, 0.60245098],
        [0.        , 0.33333333, 0.6       ],
        [0.        , 0.3372549 , 0.60392157],
        ...,
        [0.        , 0.42882966, 0.67843137],
        [0.        , 0.43137255, 0.67843137],
        [0.        , 0.43529412, 0.68235294]],

       [[0.        , 0.34460784, 0.61519608],
        [0.        , 0.3372549 , 0.60735294],
        [0.        , 0.3372549 , 0.60784314],
        ...,
        [0.        , 0.43480392, 0.68186275],
        [0.        , 0.43529412, 0.68235294],
        [0.        , 0.43529412, 0.68235294]],

       [[0.        , 0.34901961, 0.62352941],
        [0.        , 0.34901961, 0.61960784],
        [0.        , 0.34509804, 0.61568627],
        ...,
        [0.        , 0.44335172, 0.68627451],
        [0.        , 0.44313725, 0.68627451],
        [0.        , 0.44313725, 0.68627451]],

       ...,

       [[0.77205882, 0.79558824, 0.76470588],
        [0.78431373, 0.79264706, 0.77257966],
        [0.77696078, 0

array([[[0.00000000e+00, 2.15686275e-01, 6.62469363e-01],
        [0.00000000e+00, 2.15686275e-01, 6.62469363e-01],
        [0.00000000e+00, 2.15686275e-01, 6.58823529e-01],
        ...,
        [0.00000000e+00, 4.47058824e-01, 8.94117647e-01],
        [2.75735294e-04, 4.50980392e-01, 8.94117647e-01],
        [1.72152650e-02, 4.60171569e-01, 8.81004902e-01]],

       [[3.09436275e-03, 2.26623775e-01, 6.69761029e-01],
        [3.09436275e-03, 2.26623775e-01, 6.69761029e-01],
        [3.09436275e-03, 2.26623775e-01, 6.69761029e-01],
        ...,
        [0.00000000e+00, 4.47058824e-01, 8.94117647e-01],
        [0.00000000e+00, 4.50980392e-01, 8.94117647e-01],
        [1.36555990e-02, 4.55729167e-01, 8.81004902e-01]],

       [[0.00000000e+00, 2.37837010e-01, 6.84895833e-01],
        [0.00000000e+00, 2.37837010e-01, 6.84895833e-01],
        [0.00000000e+00, 2.37837010e-01, 6.84895833e-01],
        ...,
        [0.00000000e+00, 4.49601716e-01, 8.94117647e-01],
        [0.00000000e+00, 4.53

array([[[0.        , 0.54901961, 0.87843137],
        [0.        , 0.54901961, 0.87843137],
        [0.        , 0.54901961, 0.8745098 ],
        ...,
        [0.77168352, 0.81433824, 0.90980392],
        [0.71053922, 0.78039216, 0.90458793],
        [0.74693627, 0.79607843, 0.90196078]],

       [[0.        , 0.55294118, 0.88235294],
        [0.        , 0.55294118, 0.88235294],
        [0.        , 0.55294118, 0.87843137],
        ...,
        [0.80477941, 0.83470435, 0.92097886],
        [0.75968137, 0.80612745, 0.91372549],
        [0.75906863, 0.80612745, 0.90808824]],

       [[0.        , 0.55686275, 0.88627451],
        [0.        , 0.55686275, 0.88627451],
        [0.        , 0.55686275, 0.88627451],
        ...,
        [0.78615196, 0.82904412, 0.92156863],
        [0.81911765, 0.84289216, 0.92156863],
        [0.81335784, 0.83897059, 0.91960018]],

       ...,

       [[0.93308824, 0.86445312, 0.83480392],
        [0.92916667, 0.88985141, 0.88404565],
        [0.92916667, 0

array([[[0.27955203, 0.34269541, 0.21328364],
        [0.21648284, 0.29254701, 0.17618671],
        [0.32291332, 0.46877729, 0.50113358],
        ...,
        [0.        , 0.47843137, 0.80784314],
        [0.        , 0.48627451, 0.81176471],
        [0.        , 0.49019608, 0.81960784]],

       [[0.13678721, 0.17101716, 0.06829044],
        [0.15734672, 0.23265931, 0.13854167],
        [0.29969363, 0.38835784, 0.30661765],
        ...,
        [0.        , 0.48235294, 0.80784314],
        [0.        , 0.48810652, 0.81176471],
        [0.00784314, 0.49019608, 0.81960784]],

       [[0.10603219, 0.14718472, 0.07487745],
        [0.29322917, 0.35012255, 0.21228554],
        [0.54627901, 0.59831495, 0.42775735],
        ...,
        [0.        , 0.49019608, 0.81176471],
        [0.00392157, 0.49212623, 0.81306152],
        [0.00977328, 0.49411765, 0.81960784]],

       ...,

       [[0.84705882, 0.82745098, 0.80199142],
        [0.83921569, 0.82352941, 0.80392157],
        [0.82938113, 0

array([[[0.00392157, 0.31372549, 0.63529412],
        [0.00392157, 0.31372549, 0.63529412],
        [0.00392157, 0.31746324, 0.63921569],
        ...,
        [0.        , 0.35294118, 0.66946998],
        [0.        , 0.35294118, 0.66648284],
        [0.        , 0.34901961, 0.66269914]],

       [[0.00392157, 0.32156863, 0.64313725],
        [0.00392157, 0.3254902 , 0.64705882],
        [0.00392157, 0.3254902 , 0.65098039],
        ...,
        [0.00392157, 0.36807598, 0.68235294],
        [0.00392157, 0.36470588, 0.6745098 ],
        [0.        , 0.36331189, 0.67058824]],

       [[0.        , 0.33333333, 0.65790441],
        [0.        , 0.33333333, 0.65882353],
        [0.00392157, 0.33702512, 0.6627451 ],
        ...,
        [0.00392157, 0.37647059, 0.69411765],
        [0.00392157, 0.37254902, 0.68702512],
        [0.        , 0.37254902, 0.68235294]],

       ...,

       [[0.79215686, 0.76470588, 0.70196078],
        [0.79123775, 0.76470588, 0.70980392],
        [0.80617341, 0

array([[[0.        , 0.29405637, 0.62352941],
        [0.        , 0.28627451, 0.61960784],
        [0.        , 0.28235294, 0.61568627],
        ...,
        [0.72935049, 0.7705576 , 0.88836024],
        [0.73900123, 0.78223183, 0.89785539],
        [0.78428357, 0.81568627, 0.91372549]],

       [[0.        , 0.29803922, 0.62745098],
        [0.        , 0.29411765, 0.62352941],
        [0.        , 0.29019608, 0.62147672],
        ...,
        [0.79010417, 0.81379395, 0.90588235],
        [0.78226103, 0.80971201, 0.90588235],
        [0.79212479, 0.81960784, 0.90980392]],

       [[0.        , 0.30768995, 0.63710172],
        [0.        , 0.30588235, 0.63137255],
        [0.        , 0.30196078, 0.62925858],
        ...,
        [0.7706002 , 0.80211397, 0.89803922],
        [0.78250613, 0.81560154, 0.90588235],
        [0.8       , 0.82956495, 0.90980392]],

       ...,

       [[0.9254902 , 0.91764706, 0.89803922],
        [0.92941176, 0.91764706, 0.89803922],
        [0.93514093, 0

array([[[0.5716299 , 0.50104167, 0.36770833],
        [0.58400735, 0.51341912, 0.38008578],
        [0.59151061, 0.52110907, 0.3880486 ],
        ...,
        [0.14231005, 0.7317402 , 0.84938725],
        [0.14509804, 0.7254902 , 0.84313725],
        [0.14071691, 0.72110907, 0.83875613]],

       [[0.61801471, 0.54234069, 0.40116422],
        [0.62647059, 0.55272672, 0.41176566],
        [0.62977941, 0.55505515, 0.41547181],
        ...,
        [0.15548407, 0.73333333, 0.84865196],
        [0.15548407, 0.73195466, 0.84960172],
        [0.14764093, 0.7254902 , 0.84313725]],

       [[0.64083946, 0.55294118, 0.40165154],
        [0.65159314, 0.56369485, 0.41305147],
        [0.66735696, 0.57945868, 0.4288153 ],
        ...,
        [0.20425858, 0.74442402, 0.8486826 ],
        [0.18646695, 0.73693991, 0.84476103],
        [0.1783701 , 0.73103554, 0.83921569]],

       ...,

       [[0.54280025, 0.41274223, 0.2604473 ],
        [0.54092276, 0.41705633, 0.26839576],
        [0.52386642, 0

array([[[0.47441789, 0.76461397, 1.        ],
        [0.46666667, 0.75686275, 0.99972426],
        [0.45882353, 0.74901961, 0.99607843],
        ...,
        [0.11026348, 0.32143938, 0.68732288],
        [0.09701383, 0.32156863, 0.68351716],
        [0.10579044, 0.31375134, 0.68033088]],

       [[0.4745098 , 0.7685499 , 0.99938725],
        [0.46723633, 0.76050858, 0.9991546 ],
        [0.45882353, 0.74901961, 0.99607843],
        ...,
        [0.10588235, 0.31810662, 0.68635589],
        [0.10706476, 0.31760398, 0.70895852],
        [0.10387657, 0.31110696, 0.70283299]],

       [[0.47839403, 0.77251168, 0.99607843],
        [0.47047622, 0.76078431, 0.99607843],
        [0.46228554, 0.75248162, 0.99607843],
        ...,
        [0.10542279, 0.31418505, 0.69552696],
        [0.12827819, 0.31981177, 0.66414484],
        [0.15117092, 0.34414828, 0.59449583]],

       ...,

       [[0.5635723 , 0.86096814, 0.87733513],
        [0.52754289, 0.83893995, 0.84911152],
        [0.50689051, 0

array([[[0.        , 0.41176471, 0.640625  ],
        [0.        , 0.41176471, 0.63921569],
        [0.        , 0.40468128, 0.63529412],
        ...,
        [0.        , 0.25098039, 0.48768382],
        [0.        , 0.25490196, 0.49411765],
        [0.        , 0.25490196, 0.50196078]],

       [[0.        , 0.41176471, 0.65098039],
        [0.        , 0.41568627, 0.64313725],
        [0.        , 0.41568627, 0.63921569],
        ...,
        [0.        , 0.25882353, 0.50226716],
        [0.        , 0.2627451 , 0.50415949],
        [0.        , 0.26305147, 0.50980392]],

       [[0.00392157, 0.41960784, 0.65490196],
        [0.        , 0.41568627, 0.64705882],
        [0.        , 0.41568627, 0.64313725],
        ...,
        [0.        , 0.26979167, 0.51372549],
        [0.00392157, 0.27058824, 0.51726744],
        [0.        , 0.27371324, 0.52469363]],

       ...,

       [[0.90980392, 0.8745098 , 0.85490196],
        [0.90980392, 0.8745098 , 0.85490196],
        [0.91372549, 0

array([[[0.57254902, 0.74485294, 0.95477941],
        [0.59411765, 0.76654412, 0.97647059],
        [0.61176471, 0.78406863, 0.98823529],
        ...,
        [0.76102941, 0.86495098, 0.94142157],
        [0.8002451 , 0.90588235, 0.96678922],
        [0.71642157, 0.81446078, 0.87352941]],

       [[0.58431373, 0.75686275, 0.96789216],
        [0.60747549, 0.77647059, 0.98431373],
        [0.62745098, 0.79534314, 0.99215686],
        ...,
        [0.65637255, 0.76262255, 0.83284314],
        [0.65980392, 0.75      , 0.79742647],
        [0.50147059, 0.54534314, 0.55784314]],

       [[0.59215686, 0.76862745, 0.97647059],
        [0.6189951 , 0.78762255, 0.98823529],
        [0.63921569, 0.80392157, 0.99215686],
        ...,
        [0.47426471, 0.56507353, 0.57083333],
        [0.46066176, 0.50245098, 0.50367647],
        [0.44117647, 0.46666667, 0.44767157]],

       ...,

       [[0.95294118, 0.95686275, 0.93664216],
        [0.94375   , 0.94963235, 0.93198529],
        [0.86188725, 0

array([[[0.14509804, 0.30980392, 0.50980392],
        [0.14901961, 0.31372549, 0.51764706],
        [0.15294118, 0.31764706, 0.5254902 ],
        ...,
        [0.22745098, 0.37647059, 0.55245098],
        [0.20392157, 0.30723039, 0.37389706],
        [0.17647059, 0.24313725, 0.25490196]],

       [[0.14509804, 0.31372549, 0.51372549],
        [0.14901961, 0.31372549, 0.52156863],
        [0.15294118, 0.31764706, 0.52941176],
        ...,
        [0.20392157, 0.30882353, 0.38676471],
        [0.15686275, 0.21605392, 0.21605392],
        [0.14901961, 0.19607843, 0.16764706]],

       [[0.14901961, 0.31372549, 0.51875   ],
        [0.14901961, 0.31764706, 0.5254902 ],
        [0.15294118, 0.32156863, 0.53333333],
        ...,
        [0.19607843, 0.24313725, 0.23921569],
        [0.17647059, 0.19901961, 0.14117647],
        [0.16862745, 0.19607843, 0.14509804]],

       ...,

       [[0.71764706, 0.62745098, 0.44742647],
        [0.73431373, 0.64313725, 0.46666667],
        [0.75772059, 0

array([[[0.00392157, 0.6153799 , 0.98039216],
        [0.00392157, 0.6153799 , 0.98039216],
        [0.00392157, 0.6153799 , 0.98039216],
        ...,
        [0.        , 0.59215686, 0.96470588],
        [0.        , 0.58823529, 0.96078431],
        [0.        , 0.58431373, 0.96078431]],

       [[0.        , 0.62653186, 0.98039216],
        [0.        , 0.62653186, 0.98039216],
        [0.        , 0.62653186, 0.98039216],
        ...,
        [0.        , 0.59908088, 0.96470588],
        [0.        , 0.59513586, 0.96078431],
        [0.        , 0.58823529, 0.96078431]],

       [[0.        , 0.63768382, 0.97408088],
        [0.        , 0.63768382, 0.97408088],
        [0.        , 0.64160539, 0.97647059],
        ...,
        [0.        , 0.60631127, 0.96231618],
        [0.        , 0.60238971, 0.95839461],
        [0.        , 0.59846814, 0.95839461]],

       ...,

       [[0.64604157, 0.46253064, 0.37386642],
        [0.63616393, 0.4533701 , 0.35928309],
        [0.64601764, 0

array([[[0.08082108, 0.35281863, 0.59736424],
        [0.11146121, 0.45949755, 0.79754615],
        [0.27512255, 0.47297794, 0.74846814],
        ...,
        [0.79025257, 0.83921569, 0.84871324],
        [0.7254902 , 0.82352941, 0.94760742],
        [0.71678826, 0.81960784, 0.95533088]],

       [[0.05208621, 0.08039216, 0.10128676],
        [0.14479167, 0.26114334, 0.35189951],
        [0.14698319, 0.45188515, 0.74513059],
        ...,
        [0.79094573, 0.83596814, 0.82376015],
        [0.76985294, 0.8098652 , 0.76746324],
        [0.76409027, 0.79810049, 0.73382353]],

       [[0.05778186, 0.06973039, 0.03541188],
        [0.08235294, 0.10148495, 0.05816387],
        [0.10126283, 0.17640931, 0.21215629],
        ...,
        [0.85173962, 0.75333276, 0.22214403],
        [0.81156652, 0.72120098, 0.17911975],
        [0.79810528, 0.72120098, 0.27714461]],

       ...,

       [[0.83002451, 0.81960306, 0.81911765],
        [0.76439951, 0.7526348 , 0.75992647],
        [0.70894608, 0

array([[[0.61813725, 0.89411765, 0.98823529],
        [0.61568627, 0.89264706, 0.98823529],
        [0.61421569, 0.89019608, 0.98823529],
        ...,
        [0.71372549, 0.94117647, 0.98431373],
        [0.71372549, 0.94117647, 0.98431373],
        [0.71372549, 0.94117647, 0.98431373]],

       [[0.62745098, 0.90147059, 0.98823529],
        [0.63088235, 0.89803922, 0.98431373],
        [0.63088235, 0.89803922, 0.98431373],
        ...,
        [0.72107843, 0.94289216, 0.98431373],
        [0.72107843, 0.94117647, 0.98431373],
        [0.71764706, 0.94117647, 0.98431373]],

       [[0.62745098, 0.90588235, 0.98823529],
        [0.6372549 , 0.90588235, 0.98480392],
        [0.64313725, 0.90588235, 0.98480392],
        ...,
        [0.72941176, 0.94509804, 0.98382353],
        [0.72941176, 0.94509804, 0.98431373],
        [0.72941176, 0.94509804, 0.98431373]],

       ...,

       [[0.7627451 , 0.69754902, 0.57916667],
        [0.76397059, 0.70808824, 0.60147059],
        [0.72965686, 0

array([[[0.0627451 , 0.53946078, 0.89019608],
        [0.04705882, 0.47671569, 0.81617647],
        [0.0370098 , 0.59828431, 0.93553922],
        ...,
        [0.92941176, 0.95294118, 0.98039216],
        [0.94117647, 0.96078431, 0.98431373],
        [0.94338235, 0.96078431, 0.98039216]],

       [[0.14509804, 0.52279412, 0.70563725],
        [0.06936275, 0.60784314, 0.93063725],
        [0.03921569, 0.64705882, 0.97254902],
        ...,
        [0.9372549 , 0.96078431, 0.98431373],
        [0.94509804, 0.96078431, 0.98431373],
        [0.94901961, 0.96862745, 0.98431373]],

       [[0.14117647, 0.3379902 , 0.44534314],
        [0.09411765, 0.43995098, 0.68848039],
        [0.07769608, 0.57720588, 0.86029412],
        ...,
        [0.9372549 , 0.96078431, 0.98431373],
        [0.93333333, 0.95686275, 0.98039216],
        [0.9372549 , 0.95686275, 0.98431373]],

       ...,

       [[0.90980392, 0.90980392, 0.91764706],
        [0.91764706, 0.91764706, 0.9254902 ],
        [0.92156863, 0

array([[[0.25098039, 0.50980392, 0.9254902 ],
        [0.25098039, 0.51286765, 0.92941176],
        [0.24705882, 0.51286765, 0.93333333],
        ...,
        [0.40710784, 0.46666667, 0.24607843],
        [0.44044118, 0.46311275, 0.13492647],
        [0.33160999, 0.33553156, 0.05796569]],

       [[0.25098039, 0.51764706, 0.93188572],
        [0.25098039, 0.51764706, 0.9372549 ],
        [0.25098039, 0.51764706, 0.9372549 ],
        ...,
        [0.39534314, 0.50330882, 0.40477941],
        [0.45490196, 0.49534314, 0.23259804],
        [0.40955882, 0.41627604, 0.10894608]],

       [[0.25490196, 0.52156863, 0.9372549 ],
        [0.25490196, 0.52156863, 0.94117647],
        [0.25490196, 0.5254902 , 0.94509804],
        ...,
        [0.40355392, 0.53406863, 0.49485294],
        [0.42622549, 0.49803922, 0.35625   ],
        [0.43492647, 0.46017157, 0.17389706]],

       ...,

       [[0.98823529, 0.92156863, 0.80392157],
        [0.94656863, 0.88504902, 0.77928156],
        [0.81568627, 0

array([[[0.48235294, 0.62352941, 0.54117647],
        [0.50882353, 0.65490196, 0.45588235],
        [0.51666667, 0.65      , 0.23823529],
        ...,
        [0.        , 0.44705882, 0.85490196],
        [0.        , 0.43137255, 0.84313725],
        [0.        , 0.41568627, 0.82352941]],

       [[0.53333333, 0.61960784, 0.45196078],
        [0.45490196, 0.62745098, 0.63529412],
        [0.49509804, 0.65490196, 0.5872549 ],
        ...,
        [0.        , 0.45098039, 0.8627451 ],
        [0.        , 0.43921569, 0.85098039],
        [0.        , 0.42352941, 0.83529412]],

       [[0.44705882, 0.51372549, 0.19215686],
        [0.55588235, 0.62647059, 0.3754902 ],
        [0.48921569, 0.63431373, 0.57647059],
        ...,
        [0.        , 0.45882353, 0.87058824],
        [0.        , 0.44607843, 0.85784314],
        [0.        , 0.42843137, 0.84313725]],

       ...,

       [[0.85882353, 0.83137255, 0.74509804],
        [0.88235294, 0.85490196, 0.77254902],
        [0.89411765, 0

array([[[0.46367953, 0.76470588, 0.99215686],
        [0.45490196, 0.76078431, 0.99215686],
        [0.44705882, 0.75280331, 0.99607843],
        ...,
        [0.10588235, 0.32156863, 0.68627451],
        [0.10196078, 0.31764706, 0.68235294],
        [0.09803922, 0.31372549, 0.68235294]],

       [[0.47058824, 0.76862745, 0.99215686],
        [0.4627451 , 0.76078431, 0.99215686],
        [0.45182292, 0.75294118, 0.99270833],
        ...,
        [0.10588235, 0.32156863, 0.68627451],
        [0.10196078, 0.31764706, 0.68235294],
        [0.10196078, 0.31372549, 0.67758885]],

       [[0.47843137, 0.77254902, 0.99215686],
        [0.46666667, 0.76470588, 0.99215686],
        [0.45490196, 0.75294118, 0.99215686],
        ...,
        [0.10588235, 0.32156863, 0.68235294],
        [0.11597733, 0.32457108, 0.65680147],
        [0.1432598 , 0.32849265, 0.58308824]],

       ...,

       [[0.56470588, 0.85882353, 0.8745098 ],
        [0.53235294, 0.83921569, 0.85882353],
        [0.51764706, 0

array([[[0.48199487, 0.56862745, 0.67242647],
        [0.47683824, 0.52781863, 0.60851716],
        [0.5026348 , 0.52572189, 0.46208448],
        ...,
        [0.1663737 , 0.45557598, 0.6153799 ],
        [0.159375  , 0.31194853, 0.52368068],
        [0.26906595, 0.17703163, 0.09864239]],

       [[0.4567402 , 0.55667892, 0.6567402 ],
        [0.48468137, 0.54117647, 0.58939951],
        [0.45163335, 0.46801471, 0.49691521],
        ...,
        [0.228125  , 0.50735294, 0.52830882],
        [0.13492647, 0.36862745, 0.63517157],
        [0.30076402, 0.22073951, 0.14362745]],

       [[0.4778799 , 0.57775735, 0.68756127],
        [0.459375  , 0.5310049 , 0.6080059 ],
        [0.4661152 , 0.52696078, 0.63994524],
        ...,
        [0.32224265, 0.53995098, 0.4       ],
        [0.15494217, 0.41364315, 0.65784314],
        [0.30807483, 0.24552696, 0.15919118]],

       ...,

       [[0.63111405, 0.60516046, 0.47267157],
        [0.64258578, 0.6088848 , 0.47418237],
        [0.65863396, 0

In [ ]:
import tensorflow as tf
import numpy as np

( x_train, y_train ), ( x_test, y_test ) = tf.keras.datasets.mnist.load_data()

## The MNIST Data Set is composed of 28x28 black and white pixel images of handwritten digits,
## and the corresponding number that digit represents, 0-9. This is divided into 60,000 training
## instances, and 10,000 testing instances.

train_in = np.reshape( x_train, (-1, 28, 28) ) / 255 ## This ensures that every image is shaped correctly, 28x28 pixel images
test_in = np.reshape( x_test, (-1, 28, 28) ) / 255 ## and is each pixel is scaled to be between 0 and 1.

train_out = tf.keras.utils.to_categorical( y_train, 10 ) ## This takes the digit value, and transforms it into a 1-Hot Encoding,
test_out = tf.keras.utils.to_categorical( y_test, 10 ) ## so that the digit 7 is represented with the vector [0,0,0,0,0,0,0,1,0,0], etc

train_length = train_in.shape[0] ## This should be 60,000
test_length = test_in.shape[0] ## This should be 10,000

def generate_batch( image_input, value_output, vector_output, batch_size, timesteps ):
    ## This function generates a batch of data from either training or testing data,
    ## generating a random sample of batch_size images, with the corresponding digit values
    ## and one-hot encodings of those values, where each image is taken only for the first
    ## timesteps many rows.
    
    data_values = np.zeros( [batch_size, timesteps, 28] ) ## To hold the final images, timesteps rows of 28 pixels per row
    data_length = image_input.shape[0] ## Will be either 10,000 or 60,000 depending on what is passed in
    
    indices = np.random.choice( np.arange( data_length ), batch_size, replace=False )
    ## Selects a random sample of batch_sizes indices from the indicated data set
    
    for i in range( batch_size ):
        data_values[ i, 0:timesteps, :] = image_input[ indices[i], 0:timesteps, :] ## Copies the desired rows from each randomly selected image
        
    return data_values, vector_output[ indices ], value_output[ indices ]
    ## Return the truncated images, the corresponding 1-hot encodings, and the corresponding digit values

initializer = tf.keras.initializers.VarianceScaling() ## Initializing object for constructing initial weights/biases in the network

rows_input = tf.keras.layers.Input( shape = (None, 28) ) ## The input shape will be an unspecified number of rows/timesteps, with 28 features per timestep
lstm = tf.keras.layers.LSTM( units = 50, activation = tf.nn.tanh,
    kernel_initializer = initializer, recurrent_initializer = initializer, bias_initializer = initializer )( rows_input )
    ## This builds an LSTM cell with 50 internal units, taking as input the rows_input object
    ## And, after the LSTM machinery is applied, using a tanh activation function on the output
logits = tf.keras.layers.Dense( units = 10, activation = None )( lstm )
    ## This takes as input the /last/ output from the LSTM cell when applied to the rows_input object,
    ## or the last 50-unit output that summarizes all the computaitons on all the rows up to that point.
    ## It passes those 50-values into 10-units, applying no activation function so just taking a linear function of the LSTM-Output
    ## Note, the output of logits will then be 10 values, unscaled between -infinity and infinity
probabilities = tf.keras.layers.Softmax()( logits )
    ## The logit values are transformed via softmax to 10 values between 0 and 1 that sum to 1, which
    ## we may interpret as the probabilities of belonging to each digit class

probability_model = tf.keras.Model( inputs = rows_input, outputs = probabilities )
    ## Builds a model object, taking as input the rows_input object and giving as output the corresponding 10 probabilities for each class

probability_model.compile( optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'] )
    ## The model is compiled, using the categorical_crossentropy (multi-class log loss error) as the loss function,
    ## and utilizing the adam optimizer to tweak the internal weights/biases to try to minimize loss.

def test_accuracy( timesteps ):
    data_batch, tag_batch, tag_values = generate_batch( test_in, y_test, test_out, test_length, timesteps )
    ## Generate a test batch, essentially taking the entire test data set, truncated to the indicated number of rows
    predictions = probability_model.predict( data_batch )
    ## Evaluate the model on the truncated data - giving a 10-probability prediction for each truncated image
    predicted_digits = np.argmax( predictions, axis = 1 )
    ## Assign predicted digits to each image based on the largest probability from the model
    wrong_count = np.sum(predicted_digits != tag_values)
    ## Count the number of misclassifications, comparing the predicted digits and the true tag values
    return 1 - wrong_count / test_length
    ## Accuracy is 1 - misclassification rate

def train_on_diverse( batch_size ):
    ## This function reads through the entire training data set, one batch-size at a time,
    ## selects a random number of rows to consider for each batch, and passes that data into the
    ## model fit function to try to minimizes the specified loss function
    ## Note, the input to the model is given by data_batch, the desired output of the model is given by
    ## the 1-Hot Encodings in tag_batch
    for i in range( train_length // batch_size ):
        timesteps = np.random.randint( 28 ) + 1 ## Random number between [1,2,....,27, 28]
        data_batch, tag_batch, tag_values = generate_batch( train_in, y_train, train_out, batch_size, timesteps )
        probability_model.fit( data_batch, tag_batch, epochs = 1, verbose = False )
        
print("The RNN analyzes the image of the digit from top to bottom,")
print("and the output accuracy corresponds to classification accuracy")
print("looking at the first 25\%, 50\%, 75\%, 100\% of rows respectively.")

print("Note: A completely random guess should have an accuracy of about 10\%.")

## Compute the initial accuracies of the untrained model at 7 rows, 14 rows, 21 rows, and 28 rows
accuracies = [ test_accuracy( 7 ), test_accuracy( 14 ), test_accuracy( 21 ), test_accuracy( 28 ) ]

print("Prior To Training")
print("Accuracy:", accuracies )

for i in range(100):
    train_on_diverse( batch_size = 100 ) # 1-Epoch worth of training, reading through the entire data set at various timesteps
    accuracies = [ test_accuracy( 7 ), test_accuracy( 14 ), test_accuracy( 21 ), test_accuracy( 28 ) ]
    print("Round",i,"Accuracy:", accuracies )

In [15]:
( x_train, y_train ), ( x_test, y_test ) = tf.keras.datasets.mnist.load_data()

11493376/11490434 [==============================] - 2s 0us/step


In [16]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [20]:
x_train.shape

(60000, 28, 28)

In [21]:
train_out = tf.keras.utils.to_categorical( y_train, 10 ) 

In [19]:
train_out.shape

(60000, 10)

In [22]:
import tensorflow as tf
import numpy as np

( x_train, y_train ), ( x_test, y_test ) = tf.keras.datasets.mnist.load_data()

## The MNIST Data Set is composed of 28x28 black and white pixel images of handwritten digits,
## and the corresponding number that digit represents, 0-9. This is divided into 60,000 training
## instances, and 10,000 testing instances.

train_in = np.reshape( x_train, (-1, 28, 28) ) / 255 ## This ensures that every image is shaped correctly, 28x28 pixel images
test_in = np.reshape( x_test, (-1, 28, 28) ) / 255 ## and is each pixel is scaled to be between 0 and 1.
train_out = tf.keras.utils.to_categorical( y_train, 10 ) ## This takes the digit value, and transforms it into a 1-Hot Encoding,
test_out = tf.keras.utils.to_categorical( y_test, 10 ) ## so that the digit 7 is represented with the vector [0,0,0,0,0,0,0,1,0,0], etc

digit_input = tf.keras.layers.Input( shape = (28,28) ) ## Each input image is 28x28 values
flatten_image = tf.keras.layers.Flatten()( digit_input ) ## Each image is flattened into a vector of length 784
dense_1 = tf.keras.layers.Dense( units = 100, activation = tf.nn.relu )( flatten_image ) ## The vector of length 784 is passed into a dense layer of size 100, w ReLU activation
dense_2 = tf.keras.layers.Dense( units = 50, activation = tf.nn.relu )( dense_1 ) ## And then passed into a dense layer of size 50, w ReLU activation
logits = tf.keras.layers.Dense( units = 10, activation = None )( dense_2 ) ## And finally passed into a dense layer of size 10, for each of the 10 classes
    ## Note, the activation function is None - the output is just the linear combination of the input, so the outputs are 10 values between +/- infinity
probabilities = tf.keras.layers.Softmax()( logits )
    ## The 10 logit values are passed into a softmax function, converting them to 10 exclusive probability values, to represent the probability of belonging to each
    ## class

model = tf.keras.Model( inputs = digit_input, outputs = probabilities )
    ## Builds a model object, taking as input the rows_input object and giving as output the corresponding 10 probabilities for each class
model.compile( optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'] )
    ## The model is compiled, using the categorical_crossentropy (multi-class log loss error) as the loss function,
    ## and utilizing the adam optimizer to tweak the internal weights/biases to try to minimize loss.

def generate_confusion_matrix( data, labels ):
    ## The confusion matrix represents, for each `true' class, how each data point in that class
    ## was classified. A correct classifier should yield a perfectly diagonal confusion matrix.
    mat = [ [ 0 for i in range(10) ] for j in range(10) ]
    
    predictions = np.argmax( model.predict( data ), axis = 1 )
    ## model.predict computes 10 probabilities for each data point in data, and then the argmax
    ## determines the index with the largest probability, i.e., the class with the highest likelihood
    
    for i in range( data.shape[0] ):
        mat[ labels[i] ][ predictions[i] ] += 1
        ## For each true label, increment the predicted value cound
    
    for i in range(10):
        print( "Actual Digit", i, ":", "\t".join( [ str(c) for c in mat[i] ] ) )

generate_confusion_matrix( test_in, y_test )
history = model.fit( train_in, train_out, epochs = 10 ) ## Fits to the training data, running through the data set 10 times
generate_confusion_matrix( test_in, y_test )



Actual Digit 0 : 0	67	14	0	630	34	2	2	7	224
Actual Digit 1 : 0	800	0	0	257	9	6	35	11	17
Actual Digit 2 : 0	129	0	0	728	89	3	5	4	74
Actual Digit 3 : 0	62	8	0	655	67	14	5	14	185
Actual Digit 4 : 0	213	1	0	385	70	7	18	5	283
Actual Digit 5 : 0	71	28	0	259	117	5	10	22	380
Actual Digit 6 : 0	59	0	0	690	100	1	0	1	107
Actual Digit 7 : 0	252	9	0	417	120	32	51	10	137
Actual Digit 8 : 0	146	1	0	433	96	5	44	10	239
Actual Digit 9 : 0	233	4	0	370	57	22	36	4	283
Train on 60000 samples
Epoch 1/10
60000/60000 [==============================] - 3s 48us/sample - loss: 0.2564 - accuracy: 0.9252
Epoch 2/10
60000/60000 [==============================] - 2s 40us/sample - loss: 0.1097 - accuracy: 0.9668
Epoch 3/10
60000/60000 [==============================] - 2s 38us/sample - loss: 0.0770 - accuracy: 0.9765
Epoch 4/10
60000/60000 [==============================] - 2s 38us/sample - loss: 0.0590 - accuracy: 0.9817
Epoch 5/10
60000/60000 [==============================] - 2s 38us/sample - loss: 0.0469 - accurac