In [1]:
x=[[1,2,3,4,5,6,7,8,9],[1,1,1,1,1,1,1,1,1]]
y=[[1,0,0,0],[0,0,1,0]]

In [2]:
from PIL import Image
from skimage.io import imread
from skimage import color
from skimage.transform import resize
import matplotlib.pyplot as plt
import numpy as np


In [3]:
 X = np.atleast_2d(x)

In [4]:
X

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [5]:
temp = np.ones([X.shape[0], X.shape[1]+1])

In [6]:
temp

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
temp[:, 0:-1] = X 

In [8]:
temp

array([[1., 2., 3., 4., 5., 6., 7., 8., 9., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [10]:
X = temp
y = np.array(y)

In [11]:
X

array([[1., 2., 3., 4., 5., 6., 7., 8., 9., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
y

array([[1, 0, 0, 0],
       [0, 0, 1, 0]])

In [23]:
i = np.random.randint(X.shape[0])

In [20]:
i

1

In [21]:
a = [X[i]]

In [22]:
X

array([[1., 2., 3., 4., 5., 6., 7., 8., 9., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
a

[array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])]